export const siteConfig = {
  name: "Aditya Saxena Portfolio",
  authorName: "Aditya Saxena",
  username: "aditya.saxena",
  description:
    "Aditya Saxena is a Full Stack Developer, who loves to build web applications and is passionate about learning new technologies.",
  url: "https://nbarkiya.xyz",
  links: {
    github: "https://github.com/adityasaxena-crypto",
  },
  ogImage: "aditya-img.jpg",
  keywords: [
    "Aditya Saxena",
    "Aditya Saxena Portfolio",
    "Aditya Saxena Blog",
    "Aditya Saxena Projects",
    "Aditya Saxena Experience",
    "Aditya Saxena Resume",
    "Next.js",
    "React",
    "Tailwind CSS",
    "Server Components",
    "Radix UI",
    "Shadcn",
    "Next SEO",
    "Next Server Components",
    "Next.js Portfolio",
    "Next.js Blog",
    "Next.js Starter",
  ],
};
